HealthConnectLink/HCL-FRONTEND

README.md
package.json

Closes https://github.com/HealthConnectLink/HCL-FRONTEND/issues/6.

Production build

---

src/app/results-page/results-page.component.ts
src/app/results-page/results-page.css
src/app/results-page/results-page.html

Closes https://github.com/HealthConnectLink/HCL-FRONTEND/issues/9.

adding google map to results page

---

package.json
src/app/organization-page/organization-page.component.ts
src/app/organization-page/organization-page.css
src/app/organization-page/organization-page.html
src/app/organization.service.ts
src/app/results-page/results-page.component.ts
src/app/results-page/results-page.html
src/app/search.service.ts
src/app/utils.spec.ts
src/app/utils.ts

Org availability status

---

src/app/results-page/results-page.component.ts
src/app/results-page/results-page.html

Closes https://github.com/HealthConnectLink/HCL-FRONTEND/issues/38.

centering map on searched lat/long

---

src/app/location-picker/location-picker.component.ts

closes https://github.com/HealthConnectLink/HCL-FRONTEND/issues/19.

using ngZone.run to make sure lat/long update on place_changed

---

src/app/results-page/results-page.component.ts
src/app/results-page/results-page.css
src/app/results-page/results-page.html
src/app/search.service.ts

closes #46. closes #47.
Also adds a display address for each search result.

Button styles

---

src/app/organization-page/organization-page.css
src/app/organization-page/organization-page.html
src/app/utils.spec.ts
src/app/utils.ts

Fix for https://github.com/HealthConnectLink/HCL-FRONTEND/issues/49.

coloring each service based on availability

---

src/app/organization-page/organization-page.html
src/app/results-page/results-page.css
src/app/results-page/results-page.html
src/app/services-multiselect/services-multiselect.component.css
src/app/services-multiselect/services-multiselect.component.html
src/app/services-multiselect/services-multiselect.component.ts
src/styles.css

Closes https://github.com/HealthConnectLink/HCL-FRONTEND/issues/51.
Closes https://github.com/HealthConnectLink/HCL-FRONTEND/issues/52.
Closes https://github.com/HealthConnectLink/HCL-FRONTEND/issues/58.

Mvp 1 bugs

---

src/app/app.module.ts
src/app/http.pipe.spec.ts
src/app/http.pipe.ts
src/app/organization-page/organization-page.component.spec.ts
src/app/organization-page/organization-page.css
src/app/organization-page/organization-page.html

Closes https://github.com/HealthConnectLink/HCL-FRONTEND/issues/59.
Also updated the side panel to display all of an orgs phone numbers.

Org banners

---

src/app/organization-page/organization-page.html

updated the service pages to display in 2 column format

fixed service presentation

---

src/app/organization-page/organization-page.html

Service day labels

---

src/app/app.module.ts
src/app/organization-page/organization-page.component.spec.ts
src/app/organization-page/organization-page.html
src/app/time.pipe.spec.ts
src/app/time.pipe.ts

closes https://github.com/HealthConnectLink/HCL-FRONTEND/issues/56.

adding time formatter and using it on the org page

---

src/app/observable.ts
src/app/results-page/results-page.component.spec.ts
src/app/results-page/results-page.component.ts
src/app/search.service.spec.ts
src/app/search.service.ts
src/app/services-multiselect/services-multiselect.component.ts

Closes https://github.com/HealthConnectLink/HCL-FRONTEND/issues/73.
Closes https://github.com/HealthConnectLink/HCL-FRONTEND/issues/74.

Results page services changes

---

src/app/location-picker/location-picker.css
src/app/search-page/search-page.css
src/app/search-page/search-page.html
src/styles.css

centered the dropdown/search

---

src/app/results-page/results-page.component.spec.ts
src/app/results-page/results-page.component.ts
src/app/results-page/results-page.css
src/app/results-page/results-page.html

closes https://github.com/HealthConnectLink/HCL-FRONTEND/issues/55.

highlighting pins and navigating to organization page on click

---

src/app/organization-page/organization-page.component.spec.ts
src/app/organization-page/organization-page.component.ts
src/app/organization-page/organization-page.html

closes https://github.com/HealthConnectLink/HCL-FRONTEND/issues/67.

implementing Return to Search button

---

src/app/results-page/results-page.css

got rid of other css for the results page that was screwing up the sizing.

fixed issue of map being cut off

---

src/app/services-multiselect/services-multiselect.component.css

fixed button styles

---

src/app/location-picker/location-picker.css
src/app/navigation/navigation.css
src/app/organization-page/organization-page.css
src/app/organization-page/organization-page.html
src/app/results-page/results-page.css
src/app/results-page/results-page.html
src/app/search-page/search-page.html
src/styles.css

Cleaned up CSS of all the pages. Made a more uniform CSS based on style sheet

CSS clean up

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/login-page/login-page.component.css
src/app/login-page/login-page.component.html
src/app/login-page/login-page.component.spec.ts
src/app/login-page/login-page.component.ts

Made a page/folder for login page to create login page

created login page
